services:
  minecraft:
    image: itzg/minecraft-server
    restart: always
    container_name: "mcserver"
    environment:
      ICON: "https://imgs.search.brave.com/mxWP6CeRreTSaxF4ToqAA0b8DKIdFYvcyJBNgQ-71oQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA1LzcxLzQxLzc2/LzM2MF9GXzU3MTQx/NzYwMV9NTktYZUkx/TFVrT3RqOEZoRTJF/djVsc0dIUEtZa21w/di5qcGc"
      TYPE: "PAPER"
      EULA: "TRUE"
      MOTD: "                \u00A75\u00A7n\u00A7lCHAOS YIPPE!11!!\u00A7r\n           \u00A74nether is not disabled now."
      SERVER_NAME: "Mayhem"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "2G"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "30"
      ALLOW_NETHER: "true"
      ENABLE_COMMAND_BLOCK: "true"
      VIEW_DISTANCE: "15"
      SIMULATION_DISTANCE: "10"
      PLUGINS: |
        https://hangarcdn.papermc.io/plugins/Artillex-Studios/AxGraves/versions/1.17.0/PAPER/AxGraves-1.17.0.jar
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.2.0/PAPER/ViaVersion-5.2.0.jar
        https://hangarcdn.papermc.io/plugins/pop4959/Chunky/versions/1.4.28/PAPER/Chunky-Bukkit-1.4.28.jar
        # https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        # https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://github.com/TCPShield/RealIP/releases/download/2.8.1/TCPShield-2.8.1.jar
    volumes:
      - ./minecraftserver:/data
    ports:
      - 25565:25565/tcp
      # - 19132:19132/udp
    stdin_open: true
    tty: true
