services:
  minecraft:
    image: itzg/minecraft-server
    restart: always
    container_name: "mcserver"
    environment:
      TYPE: "PAPER"
      EULA: "TRUE"
      MOTD: "                \u00A75\u00A7n\u00A7lCHAOS YIPPE!11!!\u00A7r\n           \u00A74nether is disabled for now."
      SERVER_NAME: "Mayhem"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "2G"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "30"
      ALLOW_NETHER: "false"
      ENABLE_COMMAND_BLOCK: "true"
      VIEW_DISTANCE: "15"
      SIMULATION_DISTANCE: "10"
      PLUGINS: |
        https://hangarcdn.papermc.io/plugins/pop4959/Chunky/versions/1.4.28/PAPER/Chunky-Bukkit-1.4.28.jar
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://github.com/TCPShield/RealIP/releases/download/2.8.1/TCPShield-2.8.1.jar
    volumes:
      - ./minecraftserver:/data
    ports:
      - 25565:25565/tcp
      - 19132:19132/udp
    stdin_open: true
    tty: true


  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.15
    network_mode: host
    environment:
    - SECRET_KEY=a7a6572d35462e33ac7306cc269a54bfa9ef3f01b893462d6ca6a62a23051aa7
